### ISSUE TITLE
Value::get does not function as advertized in the README

### ISSUE THREAD

**Issue by professorlava** [mayah/tinytoml#4]
README says:
```c
// For convenience way, you can use get() when you're sure that the value exists.
// If type error occurred, std::runtime_error is raised.
toml::Value v = ...;
cout << v.get<string>("foo.bar") << endl;
```

However, get is templated to return actual types rather than Value objects like so:
```c
string& s = v.get<string>("foo.bar");
cout << s << endl;
```

Fixing it to return a value as advertised wouldn't change the syntax much, and would allow us to confirm the type before getting the actual value.
```c
toml::Value& v = root.get("foo.bar");
if (v.is<string>())
    cout << v.as<string>() << endl;
```

If the original behaviour is still desired, it is probably best as an overload to Value::as since the template version has no params:
```c
string& s = v.as<string>("foo.bar");
cout << s << endl;
```

**Comment by mayah** [comment]
Thanks for the report, and sorry for late response. I didn't notice this issue mail for long..., really sorry.

When I wrote this, my intention is that get<T>(...) is a short way for find(...)->as<T>().
However, it is also reasonable that get(...) is the same as *find(...).

In my opinion, I'd like to keep the current behavior. If get(...) is the same as *find(...), get() is almost meaningless. Just use find(). Since we need to get an actual type from toml::Value when using a value, the current behavior is more convenient.

**Comment by mayah** [comment]
Updated README in 4e34224.
WONTFIX.
