### ISSUE TITLE
Add convenience function for array

### ISSUE THREAD

**Issue by zmb3** [mayah/tinytoml#7]
It would be nice if there were an easier way to get the elements from a `toml::Array`.  Since an Array is just a `std::vector<toml::Value>`, you have to manually convert each `Value` element to the underlying type.

I would like to be able to do something like this:

```cpp
toml::Value v = ...;
toml::Array arr = v.get<toml::Array>("foo");
std::vector<int> int_vec = toml::array_convert<int>(arr);

// or maybe add an additional template argument:
std::vector<int> arr = v.get<toml::Array, int>("foo");
```
Would something like this be a good candidate for the library?  

Perhaps another option would be to make `Array` a class and not an alias for vector, and then you could add `is<T>()` and `as<T>()` methods similar to `toml::Value`.

**Comment by mayah** [comment]
Sounds reasonable. However, I don't like to change `toml::Array` type.

I would like to avoid adding the second type to `get()` template, because the second type makes sense only when the first type is toml::Array. Probably, we would like to have something like `v.get<std::vector<int>>("foo")`? Isn't it more sophisticated?

**Comment by zmb3** [comment]
Yeah that sounds great!
